In [21]:
# Task 1
import numpy as np 

list = [12.23, 13.32, 100, 36.32]

arr = np.array(list)

print(arr)
print(type(arr))
print(arr.dtype)

[ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>
float64


In [3]:
# Task 2 

import numpy as np

range = np.arange(2, 11).reshape(3, 3)

print(range)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# Task 3 

import numpy as np 

zero = np.zeros(10)

print(zero)

zero[6] = 11

print(zero)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [10]:
# Task 4 

import numpy as np 

range = np.arange(12, 38)

print(range)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [20]:
# Task 5 

import numpy as np 

original = np.array([1, 2, 3, 4])
print(original)

converted = original.astype(float)
print(converted)
print(converted.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
float64


In [23]:
# Task 6 

import numpy as np

centigrade = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])

fahrenheit = centigrade * 9 / 5 + 32

fahrenheit_sample = np.array([0, 12, 45.21, 34, 99.91, 32.])

print("Values in Fahrenheit degrees:", fahrenheit_sample)
print("Values in Centigrade degrees:", centigrade)
print("Values in Fahrenheit degrees:", fahrenheit)


Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [27]:
# Task 7 

import numpy as np

original = [10, 20, 30]
print(original)

x = np.append(original, [[40, 50, 60], [70, 80, 90]])
print(x)

[10, 20, 30]
[10 20 30 40 50 60 70 80 90]


In [28]:
# Task 8 

import numpy as np

arr = np.random.rand(10)

mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev_val = np.std(arr)

print("Random Array:", arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev_val)


Random Array: [0.71298345 0.25298126 0.15778019 0.91828938 0.95925221 0.48427283
 0.13578222 0.45176924 0.95351082 0.80616781]
Mean: 0.5832789406768905
Median: 0.598628139967999
Standard Deviation: 0.31219518143151703


In [31]:
# Task 9

import numpy as np 

random = np.random.random((10, 10))
print(random)

xmin, xmax = random.min(), random.max()

print(f'min value:', xmin)
print(f'max value:', xmax)

[[0.55079349 0.566459   0.22436071 0.73726972 0.44758249 0.45501571
  0.99536219 0.53312627 0.1875904  0.55394196]
 [0.94002125 0.41578268 0.64896849 0.41256521 0.36155547 0.59893261
  0.59671814 0.02638972 0.22903513 0.26433594]
 [0.15533249 0.8685841  0.254032   0.60119519 0.21905422 0.11838258
  0.00381996 0.85924095 0.95103806 0.80443371]
 [0.98389603 0.74772695 0.44561154 0.78717978 0.765935   0.43480874
  0.56179357 0.15070167 0.68147251 0.86295222]
 [0.79093932 0.77741303 0.48390739 0.0282728  0.46033294 0.29157263
  0.12250261 0.57403814 0.45180009 0.36697902]
 [0.05371318 0.4930731  0.7044282  0.9810834  0.75878384 0.62673173
  0.06172085 0.92041014 0.67366148 0.91894828]
 [0.31775404 0.15737755 0.56368831 0.57359101 0.57220556 0.03344309
  0.47975201 0.27197655 0.61340386 0.17661424]
 [0.42947138 0.12109359 0.1280682  0.81379158 0.95815825 0.54869716
  0.83754822 0.1774976  0.45763321 0.40614441]
 [0.57723403 0.87915306 0.6613582  0.1268476  0.626802   0.29483405
  0.59709638

In [33]:
# Task 10 

import numpy as np 

randoms = np.random.random((3, 3, 3))
print(randoms)

[[[0.8839524  0.47347278 0.5353888 ]
  [0.15268689 0.98617785 0.77742022]
  [0.17629889 0.72908371 0.87015778]]

 [[0.43462131 0.93311421 0.71555237]
  [0.6080603  0.77988936 0.3465362 ]
  [0.18358759 0.46430866 0.96369074]]

 [[0.61169128 0.68776052 0.35745282]
  [0.87721587 0.24128086 0.64033679]
  [0.80842726 0.07409945 0.35980694]]]
